dist: trusty
os:
    - linux

git:
    quiet: true
branches:
    only: master
    
language: c
compiler:
    - gcc
env:
    - DESTDIR="_install"

install:
    - ./configure
    - make
    - make DESTDIR=$DESTDIR install

script:
    - make DESTDIR=$DESTDIR test
